
spring:
  application:
    name : Movie Ticketing

  datasource:
    url: jdbc:mariadb://localhost:3306/ticketing
    username: root
    password: xxxx
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always

      # email 인증 properties
#  mail:
#    host: smtp.naver.com
#    port : 465
#    username : email@naver.com
#    password : pw
#    properties:
#      mail.smtp.auth : true
#      mail.smtp.ssl.enable : true
#      mail.smtp.ssl.trust : smtp.naver.com

logging:
  level:
    org.hibernate:
      sql: debug
      type: trace
