# 참고 : https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

spring:
  application:
    name : Movie Ticketing

  #  datasource:
  #    url: jdbc:mariadb://아이피:포트/DB명
  #    username:
  #    password:
  #    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.sql: debug