
spring:
  application:
    name : Movie Ticketing

  datasource:
    url: jdbc:mariadb://localhost:3306/ticketing
    username: root
    password: xxxx
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


logging:
  level:
    org.hibernate:
      sql: debug
      type: trace