
spring:
  application:
    name : Movie Ticketing

  datasource:
    url: jdbc:mariadb://localhost:3306/ticketing
    username: root
    password: xxxxxxxx
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always

  #       email 인증 properties

  mail:
    host: smtp.gmail.com
    port: 465
    username: neko2nu@gmail.com
    password: jbcj cwgq rwbn jtkl
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

logging:
  level:
    org.hibernate:
      sql: debug
      type: trace
